sudo: required

language: generic

matrix:
  allow_failures:
    - env: LINT=1
  include:
    - os: linux
      dist: trusty
      python: "2.7"
    - os: linux
      dist: trusty
      python: "3.5"
    - os: osx
      osx_image: xcode7
      python: "2.7"
    - os: osx
      osx_image: xcode7
      python: "3.5"
    - os: linux
      dist: trusty
      python: "2.7"
      env: LINT=1
      before_install:
        #- wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        #- echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list > /dev/null
        - sudo apt-get update -qq
        - sudo apt-get install -qq clang-format-3.8
      script:
        - .travis/git-clang-format --binary clang-format-3.8 --commit $TRAVIS_BUILD_DIR > __clang-format-output
        - .travis/check-git-clang-format __clang-format-output

install:
  - make

script:
  - source setup-env.sh
  - python test/test.py
